POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "hoangtoviet",
    "password": "08032000",
    "confirmPassword": "08032000"
}

###
GET http://localhost:3000/api/auth

###

POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "username" : "hoangtoviet1",
    "password" : "08032000"
}

###
POST http://localhost:3000/api/post 
Content-Type: application/json
Authorization: b eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTYzYzNjNDRhZDNjZDcxZjMwOTZkNmQiLCJpYXQiOjE2MzM5NzA4Mjh9.DXUT5-qP9eU2yUtSlG1EAbwKAY3wyTyktlKiaj3F2Ig

{
    "title": "react",
    "content": "tesst2"
}

###
GET http://localhost:3000/api/post
Authorization: b eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY1YjZiYzQ0ODI4ZDU0NWU2YzUyNWMiLCJpYXQiOjE2MzQxMTk5Mzh9.tNCe3xOb3ShtzuxQcnMbTJ2Mc1RGaxeHGLLZTQPWmIQ
